version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: TODO
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
        - 8080:8080
    depends_on:
      - db
